project:
  type: website
  output-dir: docs

website:
  title: "Proyecto — Mi Red CAR"
  navbar:
    background: light
    collapse-below: lg
    left:
      - text: "Inicio"
        href: index.qmd

      - text: "Estudiantes"
        menu:
          - text: "Estudiante 1"
            href: Est1/index.qmd
          - text: "Red de hoteles Bogotá"
            href: Est2/index.qmd
          - text: "Estudiante 3"
            href: Est3/index.qmd
          - text: "Licenciamiento de cannabis"
            href: Est4/index.qmd
          - text: " Red hospitalaria de Bogotá y su área metropolitana"
            href: Est5/index.qmd
          - text: "Estudiante 6"
            href: Est6/index.qmd
          - text: "Estudiante 7"
            href: Est7/index.qmd
          - text: "Estudiante 8"
            href: Est8/index.qmd
          - text: "Estudiante 9"
            href: Est9/index.qmd
          - text: "Estudiante 10"
            href: Est10/index.qmd
          - text: "Estudiante 10"
            href: Est11/index.qmd
          - text: "Red fundaciones felinas"
            href: Est12/intro.qmd
          - text: "Estudiante 13"
            href: Est13/index.qmd

  page-footer:
    left: "© Curso de Programación y Lenguajes Estadísticos"

format:
  html:
    theme:
      light: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    css: styles.css
